// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXKIBCFGoTiM-LJUZC6otNN8UF8foCmvM',
    appId: '1:415138711673:web:1f8ae6f92d1a1178ed2ca8',
    messagingSenderId: '415138711673',
    projectId: 'iccc-app',
    authDomain: 'iccc-app.firebaseapp.com',
    storageBucket: 'iccc-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh5DvrzTT2spT131C2sfTxyYRw8UhWIsM',
    appId: '1:415138711673:android:2bda6538875bca9aed2ca8',
    messagingSenderId: '415138711673',
    projectId: 'iccc-app',
    storageBucket: 'iccc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPjgK2Pvb-rkRPXsibcAU88z1RjzPkmgM',
    appId: '1:415138711673:ios:770689ba245f9930ed2ca8',
    messagingSenderId: '415138711673',
    projectId: 'iccc-app',
    storageBucket: 'iccc-app.appspot.com',
    iosClientId: '415138711673-h3vmes1c658ufnfo1ngh2u3od02nkefr.apps.googleusercontent.com',
    iosBundleId: 'com.example.icccApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPjgK2Pvb-rkRPXsibcAU88z1RjzPkmgM',
    appId: '1:415138711673:ios:770689ba245f9930ed2ca8',
    messagingSenderId: '415138711673',
    projectId: 'iccc-app',
    storageBucket: 'iccc-app.appspot.com',
    iosClientId: '415138711673-h3vmes1c658ufnfo1ngh2u3od02nkefr.apps.googleusercontent.com',
    iosBundleId: 'com.example.icccApp',
  );
}
